name: midlet_store
description: "Midlet Store is a free and open-source platform for Java J2ME games, featuring a vast collection of classic and popular titles with built-in emulator integration."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  archive: ^3.6.1
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  hive: ^4.0.0-dev.2
  http: ^1.2.1
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
    - assets/badges/
    - assets/flags/
    - assets/publishers/
  uses-material-design: true