name: Release Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Analyse Branch & Build Release Bundle
    runs-on: ubuntu-latest
    env:
        TOKEN: ${{ secrets.TOKEN }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get
    
    - name: Linter Analysis
      run: flutter analyze

    - name: Build Release Packages
      run: flutter build apk --split-per-abi --dart-define=TOKEN=${{ secrets.TOKEN }}

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-bundle
        path: build/app/outputs/flutter-apk